version: '3'

services: 
    application:
        build: ./
        expose: 
            - "80"
        ports: 
            - "8080:80"
        depends_on:
            - db
    db:
        build: ./db
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - "./db/timetable.sql:/docker-entrypoint-initdb.d/1.sql"
        environment:
          MYSQL_ROOT_PASSWORD: abc
        command: --default-authentication-plugin=mysql_native_password
